init:
  - SET PATH=C:/Ruby%ruby_version%/bin;%PATH%
  - SET RAKEOPT=-rdevkit
install:
  - ruby --version
  - gem --version
  - ps: |
        if ($env:BROKEN_SSL -eq "true") {
          $(New-Object Net.WebClient).DownloadFile('https://raw.githubusercontent.com/bagder/ca-bundle/master/ca-bundle.crt', "$env:TMP/ca-bundle.crt")
          $env:SSL_CERT_FILE = "$env:TMP/ca-bundle.crt"
          Write-Host "Using SSL CA list $env:SSL_CERT_FILE" -foreground Green
        }
  - bundle install --jobs 3 --retry 3
build_script:
  - bundle exec rake compile
test_script:
  - bundle exec rake travis
environment:
  matrix:
    - ruby_version: "24-x64"
    - ruby_version: "200"
      BROKEN_SSL: true
    - ruby_version: "200-x64"
      BROKEN_SSL: true
    - ruby_version: "21"
      BROKEN_SSL: true
    - ruby_version: "21-x64"
      BROKEN_SSL: true
    - ruby_version: "22"
      BROKEN_SSL: true
    - ruby_version: "22-x64"
      BROKEN_SSL: true
    - ruby_version: "23"
      BROKEN_SSL: true
    - ruby_version: "23-x64"
      BROKEN_SSL: true
    - ruby_version: "24"
